/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SdrIndexRouteImport } from './routes/sdr/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SdrRankingRouteImport } from './routes/sdr/ranking'
import { Route as SdrProfileRouteImport } from './routes/sdr/profile'
import { Route as SdrNewRouteImport } from './routes/sdr/new'
import { Route as SdrHistoryRouteImport } from './routes/sdr/history'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminGoalsRouteImport } from './routes/admin/goals'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrIndexRoute = SdrIndexRouteImport.update({
  id: '/sdr/',
  path: '/sdr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrRankingRoute = SdrRankingRouteImport.update({
  id: '/sdr/ranking',
  path: '/sdr/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrProfileRoute = SdrProfileRouteImport.update({
  id: '/sdr/profile',
  path: '/sdr/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrNewRoute = SdrNewRouteImport.update({
  id: '/sdr/new',
  path: '/sdr/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrHistoryRoute = SdrHistoryRouteImport.update({
  id: '/sdr/history',
  path: '/sdr/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGoalsRoute = AdminGoalsRouteImport.update({
  id: '/admin/goals',
  path: '/admin/goals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/team': typeof TeamRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/sdr/history': typeof SdrHistoryRoute
  '/sdr/new': typeof SdrNewRoute
  '/sdr/profile': typeof SdrProfileRoute
  '/sdr/ranking': typeof SdrRankingRoute
  '/admin/': typeof AdminIndexRoute
  '/sdr/': typeof SdrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/team': typeof TeamRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/sdr/history': typeof SdrHistoryRoute
  '/sdr/new': typeof SdrNewRoute
  '/sdr/profile': typeof SdrProfileRoute
  '/sdr/ranking': typeof SdrRankingRoute
  '/admin': typeof AdminIndexRoute
  '/sdr': typeof SdrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/team': typeof TeamRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/sdr/history': typeof SdrHistoryRoute
  '/sdr/new': typeof SdrNewRoute
  '/sdr/profile': typeof SdrProfileRoute
  '/sdr/ranking': typeof SdrRankingRoute
  '/admin/': typeof AdminIndexRoute
  '/sdr/': typeof SdrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/team'
    | '/admin/goals'
    | '/admin/settings'
    | '/admin/team'
    | '/sdr/history'
    | '/sdr/new'
    | '/sdr/profile'
    | '/sdr/ranking'
    | '/admin/'
    | '/sdr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/team'
    | '/admin/goals'
    | '/admin/settings'
    | '/admin/team'
    | '/sdr/history'
    | '/sdr/new'
    | '/sdr/profile'
    | '/sdr/ranking'
    | '/admin'
    | '/sdr'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/team'
    | '/admin/goals'
    | '/admin/settings'
    | '/admin/team'
    | '/sdr/history'
    | '/sdr/new'
    | '/sdr/profile'
    | '/sdr/ranking'
    | '/admin/'
    | '/sdr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TeamRoute: typeof TeamRoute
  AdminGoalsRoute: typeof AdminGoalsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  SdrHistoryRoute: typeof SdrHistoryRoute
  SdrNewRoute: typeof SdrNewRoute
  SdrProfileRoute: typeof SdrProfileRoute
  SdrRankingRoute: typeof SdrRankingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SdrIndexRoute: typeof SdrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/': {
      id: '/sdr/'
      path: '/sdr'
      fullPath: '/sdr/'
      preLoaderRoute: typeof SdrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/ranking': {
      id: '/sdr/ranking'
      path: '/sdr/ranking'
      fullPath: '/sdr/ranking'
      preLoaderRoute: typeof SdrRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/profile': {
      id: '/sdr/profile'
      path: '/sdr/profile'
      fullPath: '/sdr/profile'
      preLoaderRoute: typeof SdrProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/new': {
      id: '/sdr/new'
      path: '/sdr/new'
      fullPath: '/sdr/new'
      preLoaderRoute: typeof SdrNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr/history': {
      id: '/sdr/history'
      path: '/sdr/history'
      fullPath: '/sdr/history'
      preLoaderRoute: typeof SdrHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/goals': {
      id: '/admin/goals'
      path: '/admin/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AdminGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TeamRoute: TeamRoute,
  AdminGoalsRoute: AdminGoalsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  SdrHistoryRoute: SdrHistoryRoute,
  SdrNewRoute: SdrNewRoute,
  SdrProfileRoute: SdrProfileRoute,
  SdrRankingRoute: SdrRankingRoute,
  AdminIndexRoute: AdminIndexRoute,
  SdrIndexRoute: SdrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
